pipeline {

  agent any


  environment {
    DEMO_PROJECT_HOME   =  "${env.WORKSPACE}"
    POSTGRES_BIN_DIR    = '/usr/pgsql-10/bin'
  }

  stages {

    stage ("Prepare") {
      echo "Prepare build environment"
      sh './working.sh'
    }

    stage('Build') {
      steps {
        sh './gradlew clean assemble'
      }
    }

    stage('Static Analysis') {
      steps {
        sh './gradlew sonarqube'
      }
    }

    //stage('Static Application Security Testing') {
    //  steps {
    //    sh './gradlew findSecurityBugs'
    //  }
    //  post {
    //    always {
    //      // findbugs results
    //      recordIssues enabledForFailure: true, tool: findBugs(pattern: '**/findSecurityBugs.xml')
    //    }
    //  }
    //}

    //stage('SpotBugs Analysis') {
    //  steps {
    //    sh './gradlew spotbugsmain'
    //  }
    //  post {
    //    always {
    //      // spotbugs results
    //      recordIssues enabledForFailure: true, tool: spotBugs(pattern: 'build/spotbugs/main.xml')
    //    }
    //  }
    //}

        stage('Run Quality Tools Analysis') {
      steps {
        sh './gradlew checkQualityMain'
      }
      post {
        always {
          // Quality tool results files
          recordIssues enabledForFailure: true, tool: spotBugs(pattern: 'build/reports/spotbugs/main.xml')
          recordIssues enabledForFailure: true, tool: pmdParser(pattern: 'build/reports/pmd/main.xml')
          recordIssues enabledForFailure: true, tool: checkStyle(pattern: 'build/reports/checkstyle/main.xml')
        }
      }
    }

    stage('OWASP Dependency Check') {
      steps {
         sh './gradlew dependencyCheckAnalyze'
      }
      post {
        always {
          dependencyCheckPublisher pattern: 'build/reports/dependency-check/dependency-check-report.xml'
        }
      }
    }

    // This is the stage where we deploy to production.  If any test
    // fails, we won't get here.  Note that we aren't really doing anything - this
    // is a token step, to indicate whether we would have deployed or not.  Nothing actually
    // happens, since this is a demo project.
    stage('Deploy to Prod') {
      steps {
        // just a token operation while we pretend to deploy
        sh 'sleep 5'
      }
    }

  }

}
